# Generated by Django 3.2.8 on 2021-10-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(default=1634727328.5047326)),
                ('updated_at', models.TextField(blank=True)),
                ('title', models.CharField(max_length=124)),
                ('content', models.TextField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
