# Generated by Django 3.2.9 on 2021-11-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(default=1636340265.3491578)),
                ('updated_at', models.TextField(blank=True)),
                ('title', models.CharField(max_length=124)),
                ('content', models.TextField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='user.user')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
