# Generated by Django 3.2.8 on 2021-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TextField(default=1634659121.137151),
        ),
    ]
